---

# port: 4000
# host: modals.li
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Jørgen Modalsli"
keywords:    "research, economics, inequality, social mobility, history, Norway"
description: "Income inequality and social mobility between 1865 and today"
source_link: "http://modals.li"
# favicon:     "img/favicon.ico"
# touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-86249878-1

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

